version: '2'
services:
  api-tests:
    image: golang:1.12.0-alpine3.9
    command: go test .
    #volumes:
    #  - ".:/app/src"
    depends_on:
            - mongo

  mongo:
        image: mongo
        container_name: "mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27010:27010
        command: mongod --smallfiles --logpath=/dev/null # --quiet