version: '2'
services:
    myapp:
        build: .
        container_name: "myapp"
        image: golang:1.11-alpine3.9
        ports:
            - 8082:8082
        #volumes:
        #    - .:/code
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: "mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet